"""
Generate a project-wide master SLR report aggregating all 6 question runs.
Contains the generic content (introduction, methodology, cross-question
findings, bibliography) that previously appeared in every per-question report.
"""
import os
import datetime
from collections import Counter
from langchain.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from tenacity import retry, stop_after_attempt, wait_exponential

from src.llm import get_llm
from src.synthesis.statistics import compute_statistics
from research_questions import QUESTIONS


PIPELINE_DESCRIPTION = """
The review was produced by an automated, end-to-end pipeline:

1. **Module 0 — Query & criteria builder.** A LLM converts each
   natural-language research question into optimized boolean search
   strings for each database, plus a question-specific
   inclusion/exclusion criteria document.
2. **Module 1 — Literature collection.** Five sources are queried in
   parallel: PubMed (E-utilities), OpenAlex, ArXiv, MDPI (via CrossRef),
   and Springer Nature Meta API. Results are deduplicated by DOI and
   normalized title; papers without a DOI are dropped.
3. **Module 1.5 — Venue ranking.** Each paper is enriched with its
   Scimago Journal Rank quartile (Q1–Q4) for journals, or its CORE rank
   (A*, A, B, C) for conferences.
4. **Module 2 — Qdrant indexing.** Each paper's title + abstract is
   embedded with `BAAI/bge-large-en-v1.5` and stored in a per-question
   Qdrant vector collection.
5. **Module 3 — Abstract screening.** Each paper is screened by a LLM
   against the question-specific criteria; the decision (include /
   exclude), confidence and reason are persisted.
6. **Module 4 — Full-text extraction.** For each included paper the
   PDF is fetched (publisher direct, Unpaywall fallback, supervisor-
   provided manual upload). PyMuPDF parses text, the document is
   chunked, embedded, and stored. RAG retrieves the most relevant
   chunks and the LLM extracts a structured record (animal species,
   sensor types, ML methods, performance metrics, dataset size, key
   findings). When no PDF is obtainable the extraction falls back to
   the abstract.
7. **Post-processing.** Papers are filtered to publication year ≥ 2015.
   Extracted vocabularies (sensors, ML methods, species) are normalized
   via a curated `normalization_map.json` so that synonyms (`tri-axial
   accelerometer` / `accelerometer`, `rgb camera` / `camera`, …) are
   consolidated for analysis.
8. **Module 5 — Synthesis.** This report and the six per-question
   reports are generated by injecting the computed statistics into LLM
   prompts and assembling the narrative sections.
"""


CROSS_PROMPT = ChatPromptTemplate.from_template("""
You are writing the cross-question findings of a multi-question Systematic
Literature Review on Precision Livestock Farming (PLF).

You have aggregate statistics across SIX research questions:

{cross_summary}

TASK: Write 3-4 paragraphs of narrative observations about patterns,
convergences and divergences ACROSS the six questions. Focus on:
- Which sensors/methods/animals appear consistently across questions
- Where the questions diverge (e.g. Q5 finds barriers, Q1 finds technical
  combinations)
- Quality signals (Q1 distribution of journal quartiles)
- Cross-cutting research gaps revealed by the corpus as a whole

Use the EXACT counts from the statistics. Cite questions by id (Q1, Q5, etc.).
Academic tone. Markdown. NO heading. Return only the prose.
""")


def _format_cross_summary(per_q_stats: dict[str, dict]) -> str:
    """Compact text summary of stats across the six questions for the LLM."""
    lines = []
    for qid, stats in per_q_stats.items():
        p = stats["prisma"]
        top_sensors = ", ".join(list(stats["top_sensor_types"].keys())[:5]) or "—"
        top_methods = ", ".join(list(stats["top_ml_methods"].keys())[:5]) or "—"
        top_species = ", ".join(list(stats["top_animal_species"].keys())[:3]) or "—"
        lines.append(
            f"### {qid}\n"
            f"  Identified: {p['identified']}, included: {p['included']}, "
            f"extracted: {p['extracted_total']} ({p['extracted_fulltext']} FT, "
            f"{p['extracted_abstract']} abs)\n"
            f"  Q1 journals: {stats['quartile_distribution'].get('Q1', 0)}\n"
            f"  Top sensors: {top_sensors}\n"
            f"  Top methods: {top_methods}\n"
            f"  Top species: {top_species}\n"
        )
    return "\n".join(lines)


@retry(stop=stop_after_attempt(3), wait=wait_exponential(min=2, max=30), reraise=True)
def _llm_cross_findings(cross_summary: str) -> str:
    llm = get_llm(temperature=0.3, json_mode=False)
    chain = CROSS_PROMPT | llm | StrOutputParser()
    return chain.invoke({"cross_summary": cross_summary})


def _aggregate_top_extractions(per_q_stats: dict) -> tuple[Counter, Counter, Counter]:
    """Pool the top fields across all questions into single counters."""
    sensors, methods, species = Counter(), Counter(), Counter()
    for stats in per_q_stats.values():
        for k, v in stats["top_sensor_types"].items():    sensors[k] += v
        for k, v in stats["top_ml_methods"].items():      methods[k] += v
        for k, v in stats["top_animal_species"].items():  species[k] += v
    return sensors, methods, species


def _aggregate_bibliography(per_q_stats: dict) -> list[dict]:
    """Collect unique papers (by DOI) across all included corpora."""
    seen: dict[str, dict] = {}
    for stats in per_q_stats.values():
        for p in stats["included_papers"]:
            doi = (p.get("doi") or "").lower().strip() or p.get("paper_id")
            if doi and doi not in seen:
                seen[doi] = p
    return list(seen.values())


def generate_master_report(output_path: str | None = None) -> str:
    print("[Master] Computing statistics for each question...")
    per_q_stats: dict[str, dict] = {}
    for q in QUESTIONS:
        try:
            per_q_stats[q["id"]] = compute_statistics(q["id"])
        except Exception as e:
            print(f"  Skipping {q['id']}: {e}")
            continue

    if not per_q_stats:
        raise RuntimeError("No question stats available — run the pipeline first.")

    # PRISMA aggregate
    agg = {
        "identified":         sum(s["prisma"]["identified"]         for s in per_q_stats.values()),
        "screened":           sum(s["prisma"]["screened"]           for s in per_q_stats.values()),
        "included":           sum(s["prisma"]["included"]           for s in per_q_stats.values()),
        "excluded":           sum(s["prisma"]["excluded"]           for s in per_q_stats.values()),
        "extracted_total":    sum(s["prisma"]["extracted_total"]    for s in per_q_stats.values()),
        "extracted_fulltext": sum(s["prisma"]["extracted_fulltext"] for s in per_q_stats.values()),
        "extracted_abstract": sum(s["prisma"]["extracted_abstract"] for s in per_q_stats.values()),
    }

    sensors, methods, species = _aggregate_top_extractions(per_q_stats)

    print("[Master] Generating cross-question narrative...")
    cross_summary = _format_cross_summary(per_q_stats)
    try:
        cross_findings = _llm_cross_findings(cross_summary)
    except Exception as e:
        cross_findings = f"_(Cross-findings narrative generation failed: {type(e).__name__})_"

    # ----------------------------------------------------------- assemble MD
    md = []
    md.append("# Automated Systematic Literature Review — Precision Livestock Farming\n")
    md.append(f"**Generated:** {datetime.datetime.now().isoformat(timespec='seconds')}\n")
    md.append("\n---\n")

    md.append("\n## 1. Introduction\n")
    md.append(
        "Precision Livestock Farming (PLF) is a rapidly maturing field combining "
        "sensor instrumentation, IoT, computer vision and machine learning to "
        "monitor the health, behaviour, productivity and welfare of farm "
        "livestock in real time. The literature is fragmented across veterinary "
        "science, agricultural engineering and computer science venues, making a "
        "comprehensive overview difficult to obtain through manual review.\n\n"
        "This report is the master document of an automated Systematic Literature "
        "Review (SLR) covering six complementary research questions, organised "
        "into four thematic categories (Technical, Outcomes, Gaps, Future). "
        "Each question is documented in its own per-question report; this "
        "master report describes the methodology, presents aggregate results, "
        "and synthesises the cross-cutting observations that emerge from the "
        "combined corpus.\n"
    )

    md.append("\n### Research questions covered\n")
    for q in QUESTIONS:
        md.append(f"- **{q['id']}** ({q['category']}) — {q['text']}")
    md.append("")

    md.append("\n## 2. Methodology\n")
    md.append(PIPELINE_DESCRIPTION)

    md.append("\n## 3. Aggregate PRISMA Flow\n")
    md.append("```\n")
    md.append(f"  Records identified across 6 questions     : {agg['identified']:>5}\n")
    md.append(f"  Records screened                          : {agg['screened']:>5}\n")
    md.append(f"  Records included                          : {agg['included']:>5}\n")
    md.append(f"  Records excluded                          : {agg['excluded']:>5}\n")
    md.append(f"  Extractions completed                     : {agg['extracted_total']:>5}\n")
    md.append(f"    from full PDF                           : {agg['extracted_fulltext']:>5}\n")
    md.append(f"    from abstract only (PDF unavailable)    : {agg['extracted_abstract']:>5}\n")
    md.append("```\n")

    md.append("\n## 4. Per-question summary\n")
    md.append("| Question | Category | Identified | Included | FT | Abstract | % Q1 |\n")
    md.append("|---|---|---:|---:|---:|---:|---:|\n")
    for q in QUESTIONS:
        s = per_q_stats.get(q["id"])
        if not s:
            continue
        p = s["prisma"]
        q1 = s["quartile_distribution"].get("Q1", 0)
        q1_pct = (q1 / p["included"] * 100) if p["included"] else 0
        md.append(
            f"| {q['id']} | {q['category']} | {p['identified']} | "
            f"{p['included']} | {p['extracted_fulltext']} | "
            f"{p['extracted_abstract']} | {q1_pct:.0f}% |"
        )
    md.append("")

    md.append("\n## 5. Aggregate top extractions (across all included papers)\n")

    def _table(name: str, c: Counter, n: int = 15):
        if not c:
            return
        md.append(f"\n### 5.{name}\n")
        md.append("| Value | Count |\n|---|---:|\n")
        for k, v in c.most_common(n):
            md.append(f"| {k} | {v} |")
        md.append("")
    _table("1 Animal species", species)
    _table("2 Sensor types",   sensors)
    _table("3 ML methods",     methods)

    md.append("\n## 6. Cross-question Findings\n")
    md.append(cross_findings + "\n")

    md.append("\n## 7. Combined References\n")
    bib = _aggregate_bibliography(per_q_stats)
    md.append(f"Unique papers (deduplicated by DOI): **{len(bib)}**\n")
    for paper in sorted(bib, key=lambda p: ((p.get("year") or 0), p.get("title") or ""), reverse=True):
        authors = "; ".join((paper.get("authors") or [])[:3])
        if len(paper.get("authors") or []) > 3:
            authors += " et al."
        venue = paper.get("venue_name") or "—"
        rank = paper.get("quartile") or paper.get("conference_rank") or "—"
        doi = paper.get("doi") or "—"
        md.append(
            f"- **{paper.get('title', 'Untitled')}** ({paper.get('year', '?')})  \n"
            f"  {authors}. *{venue}* [{rank}]. DOI: {doi}\n"
        )

    text = "\n".join(md)

    if output_path is None:
        output_path = os.path.join("data", "runs", "master_report.md")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[Master] Saved: {output_path}")
    return text
